apiVersion: v1
kind: Secret
metadata:
  name: rds-credentials
  namespace: default
  labels:
    app: digital-store
    type: database-credentials
type: Opaque
data:
  DB_NAME: ZGlnaXRhbHN0b3Jl    # digitalstore in base64
  DB_USERNAME: ZGV2b3Bz      # devops in base64
  DB_PASSWORD: cGFzc3dvcmQ=   # password in base64 (replace with actual secure password)
  DB_HOST: ZGlnaXRhbC1zdG9yZS1kYi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=  # digital-store-db.us-east-1.rds.amazonaws.com in base64 (example)
  DB_PORT: NTQzMg==  # 5432 in base64 