apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: default
type: Opaque
data:
  REDIS_HOST: ${ELASTICACHE_ENDPOINT}  # À remplacer par l'endpoint ElastiCache encodé en base64
  REDIS_PORT: NjM3OQ==  # 6379 en base64
  REDIS_PASSWORD: ${REDIS_AUTH_TOKEN}  # À remplacer par le token d'auth encodé en base64 