appName: digital-store

backend:
  replicas: 1
  image:
    repository: "797394900921.dkr.ecr.us-east-1.amazonaws.com/digital-store/backend"
    tag: "latest"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

frontend:
  replicas: 1
  image:
    repository: "797394900921.dkr.ecr.us-east-1.amazonaws.com/digital-store/frontend"
    tag: "latest"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

secrets:
  rds:
    name: rds-credentials
configMap:
  name: digital-store-config 