apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: digital-store
    tier: frontend
  ports:
    - port: 3000
      targetPort: 3000
      name: http 