apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
data:
  # Encodage base64 (exemples)
  POSTGRES_USER: "YWRtaW4="               §§§§§§§§§§§§§§§
  POSTGRES_PASSWORD: "U3VwZXJTZWNyZXRQYXNzMTIzIQ=="   §§§§§§§§§§§§§§§§§
  POSTGRES_DB: "bXlkYg=="                     §§§§§§§§§§§§§§§§§§§§
  POSTGRES_HOST: "bXktcG9zdGdyZXMtZGIueHh4eHguYW1hem9uYXdzLmNvbQ=="        §§§§§§§§§§§§§§§§
