apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
data:
  # Note: Ces valeurs sont des exemples. En production, utilisez des valeurs sécurisées et encodées en base64
  POSTGRES_USER: "ZGlnaXRhbHN0b3Jl"  # digitalstore
  POSTGRES_PASSWORD: "ZGlnaXRhbHN0b3JlcGFzcw==" # digitalstorepass
  POSTGRES_DB: "ZGlnaXRhbHN0b3Jl"  # digitalstore
  POSTGRES_HOST: "ZGlnaXRhbHN0b3JlLXBvc3RncmVzLnJkcy5hbWF6b25hd3MuY29t" # digitalstore-postgres.rds.amazonaws.com
