apiVersion: v1
kind: Service
metadata:
  name: mon-application-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mon-application
  ports:
    - port: 8080
      targetPort: 8080
      name: http
