apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
data:
  POSTGRES_DB: ZGlnaXRhbHN0b3Jl    # digitalstore en base64
  POSTGRES_USER: cG9zdGdyZXM=      # postgres en base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=   # password en base64
  POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ==  # postgres-service en base64 