apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  namespace: default
  labels:
    app: {{ .Values.appName }}
    tier: backend
spec:
  selector:
    app: {{ .Values.appName }}
    tier: backend
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend
  namespace: default
  labels:
    app: {{ .Values.appName }}
    tier: frontend
spec:
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP 