apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend-service
  labels:
    app: {{ .Values.appName }}
    tier: backend
spec:
  selector:
    app: {{ .Values.appName }}
    tier: backend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend-service
  labels:
    app: {{ .Values.appName }}
    tier: frontend
spec:
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  ports:
  - port: 80
    targetPort: 80 