apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend-service
spec:
  selector:
    app: {{ .Values.appName }}-backend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend-service
spec:
  selector:
    app: {{ .Values.appName }}-frontend
  ports:
  - port: 80
    targetPort: 80 